In [2]:
import numpy as np

In [22]:
#. 將下兩列array存成npz檔
array1= np.array(range(30))
array2= np.array([2,3,5])
with open('multi_array.npz', 'wb') as f:
    np.savez(f,a=array1,b=array2)
npzfile=np.load('multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [27]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
print(npzfile['a'])
print(npzfile['b'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [37]:
array3 = np.array([[4,5,6], [1,2,3]])
with open('multi_array.npz','wb') as Y:
    np.savez(Y, a=array1,b=array2,c=array3)
npzfile=np.load('multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [38]:
print(npzfile['a'])
print(npzfile['b'])
print(npzfile['c'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
