In [1]:
import numpy as np

In [8]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
print(array2)
A=array1@array2
print(A)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]


In [13]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(A)
#特徵值 
print(w)
#特徵向量 
print(v)

[1. 1.]
[[1. 0.]
 [0. 1.]]


In [14]:
#3. 運用上列array計算SVD?
np.linalg.matrix_rank(A)

2